# Generated by Django 3.1.2 on 2020-10-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newplo1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_for_admin',
            name='content_of_news',
        ),
    ]
