# Generated by Django 3.1.2 on 2020-10-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newplo1', '0002_remove_news_for_admin_content_of_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_for_admin',
            name='content_of_news',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news_for_admin',
            name='image',
            field=models.ImageField(default=3, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news_for_admin',
            name='news_about',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
    ]
