# Generated by Django 3.1.2 on 2020-11-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newplo1', '0004_news_for_admin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_for_admin',
            name='site_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
